title: "paciosoft - portfolio"
description: "My personal portfolio and blog"
minima:
  skin: dark
author: "Giacomo Pacini"
collections:
  projects:
    output: true
    sort_by: prior

sass:
  #sass_dir: _sass/
  load_paths:
    - /assets/css