title: "paciosoft - portfolio"
description: "My personal portfolio and blog"
minima:
  skin: dark
author: "Giacomo Pacini"
collections:
  projects:
    output: true
    #https://talk.jekyllrb.com/t/collections-dont-order-properly-on-github-pages/4652
    sort_by: priority  #sort_by does not work on GH pages because it uses an old version of Jekyll

sass:
  #sass_dir: _sass/
  load_paths:
    - /assets/css