title: "paciosoft - portfolio"
description: "My personal portfolio and blog"
contact-mail: "mailto:giacomo@paciosoft.com"
permalink: /:year/:month/:day/:title:output_ext
minima:
  skin: dark
author: "Giacomo Pacini"
collections:
  projects:
    output: true
    #https://talk.jekyllrb.com/t/collections-dont-order-properly-on-github-pages/4652
    sort_by: priority  #sort_by does not work on GH pages because it uses an old version of Jekyll
  how-tos:
    output: true
  pubblications:
    output: true

sass:
  #sass_dir: _sass/
  load_paths:
    - /assets/css